### ISSUE TITLE
PSQLException during 2Pack installation

### ISSUE THREAD

**Issue by muhammedsha** [ingeint/ingeint-idempiere-payroll#2]
15:06:06.151-----------> Incremental2PackActivator.packIn: Installing com.ingeint.idempierePayroll /META-INF/2Pack_5.3.0.zip ... [96]
15:06:06.163 PipoDictionaryService.merge: zipFilepath->/tmp/com.ingeint.idempierePayroll_11827384292962527440_2Pack_5.3.0.zip [96]
15:06:06.179 PipoDictionaryService.merge: dict file->/tmp/2Pack_5.3.0/dict/PackOut.xml [96]
15:06:07.788===========> SQLStatementElementHandler.startElement: SQLStatement [96]
org.postgresql.util.PSQLException: ERROR: syntax error at or near "MODIFY"
  Position: 21; State=42601; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:258)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeUpdate(NewProxyStatement.java:410)
	at org.adempiere.pipo2.handler.SQLStatementElementHandler.startElement(SQLStatementElementHandler.java:86)
	at org.adempiere.pipo2.PackInHandler.processElement(PackInHandler.java:237)
	at org.adempiere.pipo2.PackInHandler.endElement(PackInHandler.java:325)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)

15:06:07.929 PipoDictionaryService.merge: commit PipoDS_acb9cb3a-5f7f-4c5d-9d3f-290793b5be80 [96]
15:06:07.963-----------> Incremental2PackActivator.packIn: com.ingeint.idempierePayroll /META-INF/2Pack_5.3.0.zip installed [96]

**Comment by muhammedsha** [comment]
<SQLStatement type="custom">
<DBType>Postgres</DBType>
<statement>
<![CDATA[
ALTER TABLE AD_Rule MODIFY Script VARCHAR2(20000) DEFAULT NULL
]]>
</statement>
</SQLStatement>


**MODIFY** Key Word not seen in _ALTER TABLE Manual_

**Comment by ocurieles** [comment]
Hi, What branch are you using ?

**Comment by muhammedsha** [comment]
> Hi, What branch are you using ?

Master

**Comment by victorsuarezis** [comment]
This problem is because, the Query is bad for Postgres. I corrected it this way:
`ALTER TABLE AD_Rule ALTER COLUMN Script TYPE VARCHAR(20000);`
`ALTER TABLE AD_Rule ALTER COLUMN Script SET DEFAULT NULL`
### Packin:
`<SQLStatement type="custom">
        <DBType>Postgres</DBType>
        <statement>
            <![CDATA[ALTER TABLE AD_Rule ALTER COLUMN Script TYPE VARCHAR(20000)]]>
        </statement>
        <statement>
            <![CDATA[ALTER TABLE AD_Rule ALTER COLUMN Script SET DEFAULT NULL;]]>
        </statement>
    </SQLStatement>`
I attach the 2 Pack corrected. And you can also see it in my fork: https://github.com/victorsuarezis/ingeint-idempiere-payroll/tree/v9-lve
[2Pack_5.3.0.zip](https://github.com/ingeint/ingeint-idempiere-payroll/files/8008904/2Pack_5.3.0.zip)
